name: Build Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_TYPE: Debug
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Ninja
        run: |
          sudo apt-get install ninja-build
          
      - uses: actions/checkout@v4
      - name: Build project
        run: cmake -S . -B build -G "Ninja Multi-Config" && cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Test project
        working-directory: ${{ github.workspace }}/build
        run: ctest -T Test -T Coverage -C ${{ env.BUILD_TYPE }}
